### ISSUE TITLE
Merciless spread and unfitting sounds.

### ISSUE THREAD

**Issue by ZeroLevels** [Tfarcenim/CursedEarth#1]
It doesn't revert back to dirt when solid blocks are on top of it like grass does.  This causes it to spread mercilessly throughout your world under the first layer of grass.  I imagine this would make it unplayable on less powerful systems.

While the first issue can be catastrophic, another less serious issue is that it sounds like stone when placed, stepped on, and broken.

**Comment by Tfarcenim** [comment]
does this still happen in 1.3a?

**Comment by Tfarcenim** [comment]
gonna take that as a no then
