### ISSUE TITLE
[Issue] after some time, mobs spawn at 0,0,0

### ISSUE THREAD

**Issue by 4Magma** [Tfarcenim/CursedEarth#2]
Hi

I play a map called OneBlock in solo player mode.
- keep allways 1-2 chunks near start block at 0,0,65 
- build plattform at height ~37 to use a slime chunk
- have a small tower with cursed earth as mob farm
- when i press a button, lights go off and mobs appear
...
But after some playtime
- journeymap shows them at 0,0 under my plattform
- i could kill them with bow and arrow through a hole 
- they seam to stand in air
- after reload of map they disappear and new mobs spawn
  again in my farm

**Comment by Tfarcenim** [comment]
:concern: I will look at it after updating to 1.16

**Comment by Tfarcenim** [comment]
should be fixd
