### ISSUE TITLE
No config for blocking specific mob spawns

### ISSUE THREAD

**Issue by chimericdream** [Tfarcenim/CursedEarth#5]
The CurseForge page mentions that there should be a config that lets you explicitly block certain mobs from spawning on cursed earth. I wanted to use this to prevent cave centipedes from Alex's Mobs from spawning, but I am not seeing anything in the server config or even in the code. Is this something that got removed between versions?

**Comment by Tfarcenim** [comment]
It's in `tags/entity_types/blacklisted` which can be added to via datapack.
